### ISSUE TITLE
503 errors in registry 

### ISSUE THREAD

**Issue by ry** [denoland/registry#162]
I see this in the logs... 
```
2019-09-05T16:05:25.264Z	227abc7c-a730-4e1a-a609-976c12d79b5f	ERROR	Invoke Error
{
    "errorType": "Error",
    "errorMessage": "Debug Failure. False expression.",
    "stack": [
        "Error: Debug Failure. False expression.",
        "    at mergeSymbol (/var/task/node_modules/typescript/lib/typescript.js:32124:26)",
        "    at /var/task/node_modules/typescript/lib/typescript.js:32235:47",
        "    at Map.forEach (<anonymous>)",
        "    at mergeSymbolTable (/var/task/node_modules/typescript/lib/typescript.js:32233:20)",
        "    at mergeModuleAugmentation (/var/task/node_modules/typescript/lib/typescript.js:32248:17)",
        "    at initializeTypeChecker (/var/task/node_modules/typescript/lib/typescript.js:59777:25)",
        "    at Object.createTypeChecker (/var/task/node_modules/typescript/lib/typescript.js:31979:9)",
        "    at Object.getTypeChecker (/var/task/node_modules/typescript/lib/typescript.js:89909:79)",
        "    at parse (/var/task/analyze_code.js:52:31)",
        "    at annotate (/var/task/analyze_code.js:16:17)"
    ]
}
```

also 
```
2019-09-05T16:15:33.261Z	630c4145-e3b6-4dd9-acc7-e956b92cf28c	ERROR	Invoke Error
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'type' of undefined",
    "stack": [
        "TypeError: Cannot read property 'type' of undefined",
        "    at getEntry (/var/task/utils.js:31:16)",
        "    at proxy (/var/task/app.js:21:17)",
        "    at Runtime.lambdaHandler [as handler] (/var/task/app.js:51:18)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}
```

A good test case is to try to load http://localhost:4000/std@v0.17.0/testing/mod.ts when running locally. Seem that there's an UnhandledPromiseRejectionWarning

**Comment by j-f1** [comment]
The error seems to be caused in the `getTypeChecker` method. I’m not sure why it’s throwing, but it seems to be caused by an attempt to override `Window` in the global namespace.

**Comment by j-f1** [comment]
It seems to be independent of #151 since it’s still occurring

**Comment by j-f1** [comment]
Figured out a MCVE:

```ts
declare global {}
```

⏩ https://github.com/microsoft/TypeScript/issues/33348
